services:
  database:
    image: postgres:alpine
    container_name: condominio_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - reserva-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: 986807/gerenciador-reservas:v1
    container_name: sistema-reserva-app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - UPLOAD_DIR=/app/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./meus-uploads:/app/uploads
    networks:
      - reserva-network


networks:
  reserva-network:
    driver: bridge

volumes:
  postgres_data:
